## adapted from NASA-Openscapes.github.io
project:
  type: website

website:
  title: "Paul Julian II, PhD"
  site-url: https://swampthingecology.org/
  favicon: images/SWE_logo_small.png
  google-analytics: "UA-131175448-1"
  
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
    left: "&copy; CC-By Paul Julian II"
 
  navbar:
    logo: images/SWE_logo_small.png
    href: https://swampthingecology.org/
    right:
    # - text: "Home"
    #   href: index.html
    - text: "About"
      href: about.qmd
    # - text: "R-Packages"
    #   href: RPackages
    # - text: "Publications"
    #   href: Publications.qmd 
    - text: "Blog"
      href: blog.qmd    
    # right:
    - icon: github
      href: https://github.com/SwampThingPaul
    - icon: linkedin
      href: https://www.linkedin.com/in/paul-julian/
    # - icon: mastodon
    #   href: https://fosstodon.org/@SwampThingPaul
    - icon: envelope
      href: mailto:pauljulianphd@gmail.com
 #    - icon: '{{< ai google-scholar >}}'
 #      href: https://scholar.google.com/citations?user=MTXcoJYAAAAJ&hl=en
      
format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left


