---
title: "Authorship Agreement"

---

# Guidelines for Authorship<sup>1</sup>

<sup>1</sup>Adapted from the Saltmarsh Habitat & Avian Research Program ([https://www.tidalmarshbirds.org/](https://www.tidalmarshbirds.org/){target="_blank"}) Guidelines for Authorship Standard Operating Procedure.

<a href="files/Authorship_guide.pdf#" class="download" title="Download as PDF">Download as PDF</a>			

**Table of Contents:**

1. [**Authorship Criteria**](#author)

    - [*Consider Thresholds of Effort* ](#threshold)
  
    - [*Offer Further Involvement*](#involvement)
  
    - [*Use Inclusion to Deal with Uncertainty*](#inclusion)
   
    - [*Invite Alumni to Participate when Appropriate*](#alum)
   
2. [**Author Order and Etiquette**](#order)

3. [**A Living Document**](#doc)


***

Deciding authorship on scientific publications can be complicated because practices and cultural norms vary across disciplines and even across labs within the same discipline. This is especially relevant in ecology, where standardized guidelines are lacking and a diversity of options exist for deciding authorship and author order. These guidelines outline a set of criteria for authorship determinations. These criteria are presented as guidelines, because a common set of expectations is important to maintain mutual satisfaction among co- authors. We recognize, however, that some flexibility will be required and communication is essential to the process.  Before all else, remember __conversations regarding authorship for each manuscript should happen early, frequently, openly, and inclusively__. A conversation should be expected when the paper is first conceived and should be revisited periodically as each project develops.

<br>

<a name="author"></a>

## **Authorship Criteria**
Authorship on a manuscript is warranted when a researcher has made a substantial contribution to the manuscript in question (not the overall project as a whole), as defined by any __two__ of the following:

   * Conceiving of ideas and/or study design and/or analytical approach
   
   * Writing of the manuscript (or sections)
   
   * Reviewing and editing the manuscript
   
   * Analyzing data
   
   * Interpreting results
   
   * Collecting data in field or lab (except in rare circumstances this will not include temporary technicians)
   
   * Creating or managing critical databases (e.g. demographic database, historical abundance estimates spreadsheet)
   
   * Obtaining funding (e.g., proposal writing, grant management, and project reports)
   
<br>

Other things are important to keep in mind (expanded upon in the sections below).

* *A conversation is necessary for each manuscript*

* *Consider thresholds of effort (“could the study have been done without the contribution?”)*

* *Offer further involvement*

* *Use inclusion to deal with uncertainty (“better to be inclusive than to exclude”)*

* *Primary authors and their advisors/PIs/mentors will make the final decision on authorship*

* *Invite prior individuals (alumni) to participate when appropriate*

* *There are exceptions for grant deliverables.*

* ***When in doubt, talk it out!***

<br>
<br>

<a name="threshold"></a>

*Consider Thresholds of Effort* 

Ultimately, the primary author must have some leeway in making authorship decisions, and ensuring that a certain minimum threshold of contribution has been made. When the level of the contribution to the particular manuscript is unclear (e.g. as in the case of data collection), the deciding question becomes “could the study have been done without that person’s contribution?”

For instance, did the extra work amount to a few data points within a huge dataset (if the analysis was enhanced by their participation, but was possible without it, authorship may not be warranted), or were the data points critical to establishing the pattern (if the analysis is impossible without the data from this study site, or if trends depend on those data, authorship is more clearly warranted).  Other considerations: If a researcher is collecting data for a study that is not their own, did they do extra work that they would not otherwise have done on their own study site or for their own study (if so, the case for authorship increases)? Did the effort amount to a few days of fieldwork (may not warrant authorship) or a season’s worth of logistics and data collection (more clearly warrants authorship)?

<a name="involvement"></a>

*Offer Further Involvement*

In some instances, a contributor may have clearly passed a threshold of effort (see previous), but will have only contributed to one of the categories that would qualify them for consideration of authorship. In these instances, it is the primary author’s responsibility to reach out to the contributor early in the writing process and have a conversation about further involvement. The second category can be easily achieved by assistance with developing and reviewing the manuscript, and contributors that have clearly passed a threshold of effort should be given that opportunity.

<a name="inclusion"></a>

*Use Inclusion to Deal with Uncertainty*

Recognize that the contribution of effort is a gradient with clear endpoints (one data point out of two probably gets you authorship, one data point out of 1,000 probably doesn’t), so there will likely be situations where it is unclear (200 data points out of 1,000?). If there is any uncertainty in gauging the contribution, it is better to be inclusive than to exclude, and it is better to talk directly to the contributor explicitly. A quick phone call made in a spirit of inclusion can almost always improve the situation for everyone, both for this manuscript and for future collaboration.

<a name="alum"></a>

*Invite Alumni to Participate when Appropriate*

As data collected by others who have moved on are used in analysis, we need to give them credit for their prior work.  If the data have already been published in another form and their papers can be cited, this may be enough. Authorship may be warranted or offered, however, under several circumstances.  First, if the individual was involved in the conception of the ideas in the new manuscript, this would warrant their inclusion. Second, if the new manuscript is based largely on the data (or conceptual groundwork) of a single individual (similar to the rules for contemporary contributors, could the analysis be completed without their data?), authorship should be considered. If the previous work of prior individuals passes the Threshold of Effort test for any reason, the burden is on the PI involved to offer the opportunity for further engagement in the new manuscript to new individuals, preferably early in the process. If prior individuals respond positively and stay involved, then they should be authors on the new work. Prior individuals are responsible for deciding to stay engaged and following through with their involvement. Importantly, prior individuals should understand that if they do not respond to inquiries about authorship, historical datasets can still be used, but they will not be included as authors. This same approach may be followed for the advisors of prior individuals if they pass the Threshold.

<a name="order"></a>

## **Author Order and Etiquette**
The order of authors on publications will follow the practice of first-last author emphasis. The first author will be the person who did the majority of the work, carried out the study, and will often be a the primary writer of the manuscript. Typically, the last author should be the lab PI.  “Credit” or “importance” is attributed to authors in the following order:  first, last, 2<sup>nd</sup>, 3<sup>rd</sup>, 4<sup>th</sup>, etc.  Final decisions regarding author order ultimately lie with the first author, in consultation with their advisor, PI or mentor. Authors that disagree with the draft author order, however, should feel comfortable voicing their concerns. More importantly, primary authors should ask specifically for co-authors to approve the final order via email.

Anyone listed as an author must be given a fair opportunity to read and comment on the manuscript.  If prospective authors do not respond in a reasonable amount of time, they should be removed, barring exceptional circumstances (the response could be as simple as “manuscript is good to go”, as long as the author acknowledges and approves the content). The lead author should give AT LEAST two weeks for the response period and should specify a date by which comments are due. Two corollaries of this guideline are 1) anyone has the right to request removal as author from a paper for any reason, including a personal judgment of failure to cross the Threshold for Effort, and 2) no one should ever be an author on a manuscript where they did not approve the final submitted draft (note that many journals have this requirement).

It is the primary author’s responsibility, as corresponding author, to provide all co-authors with:

*	A digital version of the final submitted draft

*	News of all significant correspondence with the editor/publisher

*	The opportunity to assist with revisions

*	A digital version of all revisions submitted for publication and the responses to reviewers

*	Page proofs and the opportunity to comment on them

*	A final pdf of all published papers

<a name="doc"></a>

##	**A Living Document**
Expectations for authorship are a set of evolving cultural norms. This means that 1) they must be taught anew to each set of students and/or new individual early in their involvement with the project and 2) the guidelines in this document need to be revisited and updated regularly (~annually or as needed).

***
<!---
## For Fun

When authorship is equal and all participating authors opt for random author order (and everyone participated equally) you can draw names out of a hat...or make a hat draw in #rstats. 

```{r ,echo=T,message=F,warning=F,eval=F}

set.seed(1)

authors=c("Author_Name_1", "Author_Name_2",
          "Author_Name_3", "Author_Name_4",
          "Author_Name_5", "Author_Name_6")
auth.order=c()
for(i in 1:length(authors)){
  pull=sample(authors,1);#Sample from author list
  authors=authors[!(authors%in%pull)];#Remove sampled author from existing list

  auth.order=rbind(auth.order,pull)
}
auth.order

```

***
--->