---
title: "Background"
output:
  html_document:
    includes:
      in_header: images/cv_header.html
---

<a href="files/Julian_CV_20181213.pdf#" class="download" title="Download CV as PDF">Download CV</a>			

## Education

* University of Florida, Soil and Water Sciences, PhD (2018)
* Florida Gulf Coast University, Environmental Science, MSc (2010)
* Benedictine College, Biochemistry, BSc (2005) 

## Appointments
* Everglades Technical Lead, Florida Department of Environmental Protection (2011 - Present)
* Graduate Research Assistant, University of Florida (2016 - 2018)
* Adjunct Faculty, Florida Gulf Coast University, Marine and Ecological Sciences (2015)
* Biological Scientist, Florida Fish and Wildlife Research Institute (2010 - 2011)
* Lab Manager, University of Florida (2008 - 2009)
* Graduate Research Assistant, Florida Gulf Coast University (2007 - 2008)
* Technical Director and Staff Chemist, Harbor Branch Environmental Lab (2007 - 2008)
* Staff Chemist, Mote Marine Laboratory (2005 - 2007)

## Synergistic Activities

#### Science Communication 
* Science Communication - [Biotweeps](https://biotweep.wordpress.com/) Curator. [Twitter Archive](https://t.co/QPPpk3II0G)  (September 27, 2018 - August 1, 2018).
* Frequent contribitor of content to "[#MacrophyteMonday](https://twitter.com/search?l=&q=%23MacrophyteMonday%20%20%20from%3Aswampthingpaul&src=typd)" and "[#WetlandWednesday](https://twitter.com/search?q=%23WetlandWednesday%20%20from%3Aswampthingpaul&src=typd)" on Twitter. 

#### Extracurricular 
* Long Term Ecological Research. All Scientist Meeting workshop co-organizer (2018)
* Florida Coastal Everglades Long Term Ecological Research (2018 - Present)
* Florida Coastal Everglades Long Term Ecological Research, Student Member (2016 - 2018)
* Florida Coastal Everglades Long Term Ecological Research Student Organization, Off-Campus Representative (2017 - 2018)
* Global Lake Ecological Observatory Network, Student Member (2017 - 2018)

#### Peer and Technical Review
* Peer Review: Wetlands, Journal of Agriculture, Ecotoxicology, Lake and Reservoir Management, Environmental Management, Ecological Engineering (and many more)
* Technical Review: South Florida Environmental Report, Everglades Technical Oversight Committee, Aquifer Storage and Recover Pilot Project Technical Data Review
* Working Groups and Subteams
  + Western Everglades Restoration Planning Project, Water Quality Subteam
  + Loxahatchee River Restoration Planning Project, Water Quality Subteam
  + Global Lake Ecological Observatory Network, Signal Processing Working Group
  + Florida Coastal Everglades Long Term Ecological Research, Biogeochemistry Working Group 