---
title: "Everglades Stormwater Treatment Areas"

---

The Everglades Stormwater Treatment Areas (STAs) is one of the largest treatment wetland facilities constructed. The Everglades STAs circa 2017, over 57,000 acres of former agricultural and remnant wetlands within the Everglades Agricultural Area. The primary purpose of the STAs are to provide water quality treatment to waters entering the Everglades Protection Area.

The first STA to be constructed was the Everglades Nutrient Removal Project (ENR) now STA-1W and began operation mid-1993. As a result of this initial effort, additional STAs were constructed. Overall, during the past 20 years, STAs treated approximately 17.4 million acre-feet of water with an effluent TP concentration of 32 µg/L. This is reflected in total P (TP) load reductions of 2,912 metric tons or TP load reduction of 76% ([www.sfwmd.gov/sfer](www.sfwmd.gov/sfer)).

Performance of STAs has been influenced by several factors including antecedent land use, nutrient and hydraulic loading, vegetation composition and condition, soil type, cell topography, cell size and shape, extreme weather conditions, construction activities to improve performance (enhancement activities), and regional operations. To achieve a long-term concentration of 10 µg/L TP in the downstream Everglades Protection Area, the STAs must achieve a long-term concentration of 13 µg/L (NOTE: this is an over-simplification of the STA compliance  assessment). 

In my research I address wetland function and biogeochemical processes related to the performance of the STAs. 

1. [Ecosystem Metabolism](https://swampthingpaul.github.io/ecometab.html)
2. [Wetland Ecological Stoichiometry](https://swampthingpaul.github.io/ecostoich.html)
3. Geochemical processes (_In progress_)
4. Nutrient Spiraling in wetland ecosystems (_In Progress_)

***