---
title: "Greetings!! Welcome to my webpage."
output:
  html_document:
    includes:
      in_header: images/cover_header.html
      after_body: images/cover_foot.html
---

I am an ecologist with a multi-disciplinary background focused on aquatic biogeochemistry and ecology on the landscape scale. Generally, I can be classified as an aquatic biogeochemist studying biogoechemical processes along the freshwater to marine aquatic continuum. But wetlands hold a special place in my heart.  

A couple of word to describe me: Wetland Biogeochemistry, Ecologist, Data-scientist, Soil-Scientist, Naturalist, Swamp Walker, Lover of all things R

This website will host some general information about myself, my research interests and publications.

_#rstats_ _#geospatial_ _#GIS_ _#soil_ _#ecology_ _#climatechange_ _#biogeochemistry_ _#wetland_ _#aquatic_

<div class = "row">
<div class = "col-md-6">
## Social Media

Follow me on twitter for the some recent development on manuscripts, colleagues work or oppurtunities (and some ranting). 

<a class="twitter-timeline" 
href="https://twitter.com/SwampThingPaul?ref_src=twsrc%5Etfw"
data-width="500" 
data-height="500"
data-tweet-limit="5" >
Tweets by SwampThingPaul
</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

</div>

<div class = "col-md-6">
## Words of wisdom

_“My temple is the swamp …When I would recreate myself, I seek the darkest wood, the thickest and most impenetrable and to the citizen, most dismal, swamp. I enter a swamp as a sacred place, a sanctum sanctorum… I seemed to have reached a new world, so wild a place …far away from human society. What’s the need of visiting far-off mountains and bogs, if a half-hour’s walk will carry me into such wildness and novelty.”_

*Henry David Thoreau*, _Walden and Other Writings_

</div>

***