---
  title: "Presentations"
  paged-footnotes: true
---

All presentations are available upon request, some are available here. 

Multiple technical presentations not listed here have been presented at meetings including technical, environmental policy, restoration project planning and general public audiences.

- **Julian, P.** 2019. Everglades Restoration and Water Quality. Coccoloba Chapter of the Florida Native Plant Society. Guest Speaker.  
  - [pdf Link](SwampThingPaul.github.io/files/pres/20190321_Everglades.pdf){target="_blank"}
  - [YouTube Link](https://youtu.be/4YLTccWeVjE){target="_blank"}

- **Julian, P.** and G. Fletcher. 2018. Don't wave the river red gums goodbye. The role of environmental flows in restoring river water quality and riparian zones along the Wimmera River. Society of Wetland Scientists. Denver, CO.
  -  [pdf Link](SwampThingPaul.github.io/files/pres/Julian_Fletcher_Wimmera_EFlows_postSWS.pdf){target="_blank"}
  -  [YouTube Link](https://youtu.be/k5w1YYx5r7o){target="_blank"}

- **Julian, P.**, S. Gerber. A.J. Reisinger, K. Larios. 2018. Let’s take a ride downstream. Translating nutrient spiraling concepts to wetland ecosystems. Society of Wetland Scientists. Denver, CO.

- **Julian, P.**, et al. 2018. Did you guess which thing was not like the others? Evaluation of wetland nutrient stoichiometry and homeostasis in a subtropical treatment wetland. Society of Wetland Scientists. Denver, CO.

- Osborne, T.Z., M.W. Clark, **P. Julian**, N. Ward, R. Collins, E.J. Philips and P. Fletcher. 2018. Translating the effects of sea-level rise in urban systems to the coastal ecosystem interface.  12th International Symposium on Biogeochemistry of Wetlands, Coral Springs, FL.

- Villapando, O., J. King, R.K. Bhomia and **P. Julian**. 2018. Biogeochemical response of selected STA flow-ways to different flow scenarios. 12th International Symposium on Biogeochemistry of Wetlands, Coral Springs, FL.

- **Julian, P.**, et al. 2018. One of these things is not like the other. Evaluation of wetland nutrient stoichiometry and homeostasis in a subtropical treatment wetland. 12th International Symposium on Biogeochemistry of Wetlands, Coral Springs, FL.

-	Ward, N., T. Dye, **P. Julian** and T.Z. Osborne, 2017. Examining the effects of hurricanes Matthew and Irma on water quality in the inter-coastal waterway, St. Augustine, FL. American Geophysical Union. New Orleans, LA. 

- **Julian, P.**, R Bhomia, S. Gerber, and A.L. Wright. 2017. Stoichiometric relationships amongst ecosystem compartments of a treatment wetland. Southeastern Ecology and Evolution Conference. Ft Myers, FL. 

- **Julian, P.**, R. Chambers, J. Kominoski, T. Troxler, A. Wright, and T.Z. Osborne. 2017. Pyrite formation in the Coastal Everglades:  Can a fool’s gold indicate sea-level rise? SSSA Annual Meeting. Tampa, FL. 

- **Julian, P.**, R. Bhomia, A. Wright, and T.Z. Osborne. 2017. Aquatic Productivity in Subtropical Marsh along a soil nutrient gradient – An assessment of the Everglades Stormwater Treatment Areas. SSSA Annual Meeting. Tampa, FL.

-	Osborne, T.Z., R. Bhomia, **P. Julian// and K.R. Reddy. 2017. Spatial Distribution of Soil Biogeochemical Properties in Stormwater Treatment Area 3/4 Cells 3A and 3B. SSSA Annual Meeting. Tampa, FL.

- **Julian, P.**, R. Bhomia, A. Wright and T.Z. Osborne. 2017. Aquatic Productivity in Subtropical Marsh – Observations from the Everglades Stormwater Treatment Areas. 2017 Society of Wetland Scientist Annual Meeting, San Juan, Puerto Rico.

- **Julian, P.**, B. Gu and A. Freitag. 2017. Limiting Factors in Mercury Methylation Hotspot Development: The Tangled Web. Greater Everglades Ecosystem Restoration, Coral Spring, FL.

- **Julian, P.**, K. Larios and P. Julian 2017. Data Integration and Synthesis Framework for Understanding the Phosphorus Cycling and Reduction Mechanisms in STA Flow-ways. Greater Everglades Ecosystem Restoration, Coral Spring, FL.

-	Gu, B and **P. Julian**. 2017. High Biotic Mercury in South Florida Wetlands: Fish Trophic Position and Wading Bird Redistribution. Greater Everglades Ecosystem Restoration, Coral Spring, FL.

-	Villapando, O., R. Bhomia, J. King and **P. Julian**. 2017. Water Quality Along inflow to Outflow Gradient of the Everglades Stormwater Treatment Areas. Greater Everglades Ecosystem Restoration, Coral Spring, FL.

-	**Julian, P.**, B. Gu, K. Weaver and A. Wright. 2016. Status and Trends of Landscape-Scale Mercury in South Florida and the Everglades. 7th SETAC World Congress/SETAC North America 37th   Annual Meeting. Orlando, FL.

-	Osborne, T.Z., L.T. Simpson, T.B. Schafer, M. Camacho, **P. Julian II**, N.D. Ward, and L. Laplaca. 2016. Alteration of hydrology by mangrove encroachment in saltmarsh ecosystems and potential impacts to ecosystem services. Ecological Society of America, Fort Lauderdale, FL.

-	Osborne, T.Z., L.T. Simpson, T.B. Schafer, M. Camacho, **P. Julian II**, N.D. Ward, and L. Laplaca. 2016. Carbon biogeochemical processes along a Mangrove-Salt Marsh ecotone. Mangrove & Macrobenthos Meeting 4, St Augustine, FL. 

-	**Julian, P.**, T.Z. Osborne, J. Castro, J. Sadle and L.R. Ellis. 2016. Interpreting effects of water management on soil nutrient cycling in an oligotrophic subtropical wetland. Society of Wetland Scientist Annual Meeting. Corpus Christi, TX.

- **Julian, P.** and A. Wright. 2016. Can soil nutrient stoichiometry determine mercury hotspot formation in a subtropical peatland? An Everglades case study. Society of Wetland Scientist Annual Meeting. Corpus Christi, TX.

- **Julian, P.** 2016. Hydrologic restoration of the Taylor Slough Region of Everglades National Park. Changes in water quality and implications for ecosystem management. 5th University of Florida Water Institute Symposium. Gainesville, FL.

- **Julian, P.**, B. Gu, G. Redfield, and K. Weaver. 2015. An Overview of Everglades Mercury Issues: Critical Questions Remain. Greater Everglades Ecosystem Restoration, Coral Spring, FL.

-	Gu, B., **P. Julian** and G. Redfield. 2015. Spatial and Temporal Variation of Total Mercury in Mosquitofish from Everglades Marshes. Greater Everglades Ecosystem Restoration, Coral Spring, FL.

- **Julian, P.** 2014. Large-Scale Water Quality Improvement Projects: An Everglades Perspective. SLER Con 2014. Orlando, FL.

- **Julian, P.**, E.M. Everham, and M.B. Main. 2012. Influence of a large-scale removal of an invasive plant (Melaleuca quinquenervia) on home range size and habitat selection by female Florida panthers (Puma concolor coryi) within Big Cypress National Preserve. 75th Florida Academy of Science Annual Meeting. Tampa, FL.

- **Julian, P.**, E.M. Everham, A.E. Hartley, M.B. Main and J. Burch. 2010 Reduction of Home Range Size by the Florida Panther Following Melaleuca Removal in Big Cypress National Preserve. 15th Annual Exotic Species Workshop for Southwest Florida. Ft Myers, FL.

- **Julian, P.**, et al. 2008. Melaleuca research at Florida Gulf Coast University. 13th annual Exotics Species Workshop for Southwest Florida. Ft Myers, FL.

- **Julian, P.**, M. Atteberry and P. Steinbach. 2005.  The Quantitative Study of Mercury in Atchison Area Water Sources. Atchison, KS. 

